"""init

Revision ID: 730e3c52992e
Revises: 
Create Date: 2022-05-02 10:26:40.831806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730e3c52992e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('text_question', sa.Text(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('date_create_quesstion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_question')
    # ### end Alembic commands ###
