"""Initial

Revision ID: 939b61019cef
Revises: 
Create Date: 2022-05-02 14:16:07.454323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939b61019cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('text_question', sa.Text(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('date_create_question', sa.DateTime(timezone='UTC'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_question')
    # ### end Alembic commands ###
